services:
  kroki:
    image: yuzutech/kroki
    ports:
      - "8000:8000"
    environment:
      KROKI_MERMAID_HOST: mermaid
    restart: unless-stopped

  mermaid:
    image: yuzutech/kroki-mermaid
    expose:
      - "8002"
    restart: unless-stopped
