@startuml
autonumber
skinparam sequenceMessageAlign center
participant "HSS" as HSS
participant "MME" as MME
participant "S-GW" as SGW
participant "P-GW" as PGW
participant "PCRF" as PCRF
participant "eNodeB" as ENB
participant "UE" as UE

== Subscription Update ==
HSS -> MME: Diameter (S6a): Insert-Subscriber-Data-Request (IDR)
MME -> HSS: Diameter (S6a): Insert-Subscriber-Data-Answer (IDA)

group QCI, ARP, or APN-AMBR changed
    == Bearer Modification Command ==
    MME -> SGW: GTPv2: Modify Bearer Command
    SGW -> PGW: GTPv2: Modify Bearer Command

    opt Dynamic PCC is deployed
        PGW -> PCRF: Diameter (Gx): Credit-Control-Request (CCR) UPDATE_REQUEST
        PCRF -> PGW: Diameter (Gx): Credit-Control-Answer (CCA)
    end

    == Bearer Modification Request ==
    PGW -> SGW: GTPv2: Update Bearer Request
    SGW -> MME: GTPv2: Update Bearer Request

    MME -> ENB: S1AP: E-RAB Modify Request (NAS: Modify EPS Bearer Context Request)
    ENB -> UE: RRC: Connection Reconfiguration
    UE -> ENB: RRC: Connection Reconfiguration Complete
    ENB -> MME: S1AP: E-RAB Modify Response

    UE -> ENB: RRC: Direct Transfer (Modify EPS Bearer Context Accept)
    ENB -> MME: S1AP: Uplink NAS Transport (Modify EPS Bearer Context Accept)

    == Bearer Modification Acknowledgement ==
    MME -> SGW: GTPv2: Update Bearer Response
    SGW -> PGW: GTPv2: Update Bearer Response

    opt Dynamic PCC is deployed
        PGW -> PCRF: Diameter (Gx): Credit-Control-Request (CCR)
        PCRF -> PGW: Diameter (Gx): Credit-Control-Answer (CCA)
    end
end
@enduml
